class Workbench:
	def workbench:
		Campsite
		WOrkbench
		Campfire
		CarpentryTable
		ResearchTable
		ButcheryTable
		WainwrightTable
		FarmersTable
		Fishery
		MasonryTable
		Kiln
		Bloomery
		Mill
		Anvil
		Sawmill
		BlastFurnace
		CementKiln
		BakeryOven
		CastIronStove
		Kitchen
		TailoringTable
		MachinistTable
		ScrewPress
		Lathe
		Shaper
		AssemblyLine
		ElectricMachinistTable
		ElectricStampingPress
		ElectricLathe
		ElectricPlaner
		PumpJack
		OilRefinery
		ElectronicsAssembly
		RoboticAssemblyLine
		RollingMill
		Laboratory
		SpinMelter
		AutomaitcLoom